/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import dashboard.customerDashboard;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RageKing
 */
public class bookingList extends javax.swing.JFrame {

    /**
     * Creates new form bookingList
     */
    public bookingList() {
        initComponents();
        displayTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  public void displayTable() {
    try {
        config.dbConnector connector = config.dbConnector.getInstance();
        int sessionID = config.Session.getInstance().getId();
        
        DefaultTableModel model = (DefaultTableModel) bookingTable.getModel();
        // Set Headers if not set in GUI builder
        model.setColumnIdentifiers(new String[]{"Booking ID", "Route", "Status", "Total Price"});
        model.setRowCount(0); 

        // Simplified query for the list view
        String query = "SELECT b_id, pick_up, destination, status, total_price FROM tbl_bookings " +
                       "WHERE a_id = " + sessionID + " ORDER BY b_id DESC";

        java.sql.ResultSet rs = connector.getData(query);
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("b_id"),
                rs.getString("pick_up") + " to " + rs.getString("destination"),
                rs.getString("status"),
                "₱" + String.format("%.2f", rs.getDouble("total_price"))
            });
        }
    } catch (java.sql.SQLException ex) {
        System.out.println("Error loading table: " + ex.getMessage());
    }
}
  
  private void openDetails(int bookingId) {
    config.Session sess = config.Session.getInstance();
    config.dbConnector connector = config.dbConnector.getInstance();
    
    try {
        // 1. Fetch the main booking row
        String bookingQuery = "SELECT * FROM tbl_bookings WHERE b_id = " + bookingId;
        java.sql.ResultSet rs = connector.getData(bookingQuery);
        
        if (rs.next()) {
            String bid = String.valueOf(rs.getInt("b_id"));
            String fullName = sess.getFirstname() + " " + sess.getLastname();
            String pUp = rs.getString("pick_up");
            String dest = rs.getString("destination");
            String sDate = rs.getString("start_date");
            String eDate = rs.getString("end_date");
            String tPrice = "₱" + rs.getDouble("total_price");
            String stat = rs.getString("status");
            String vanIdsString = rs.getString("van_id"); // e.g., "1,2"

            // 2. Fetch all vans associated with this booking
            java.util.List<config.VanModel> vans = new java.util.ArrayList<>();
            if (vanIdsString != null && !vanIdsString.isEmpty()) {
                String vanQuery = "SELECT * FROM tbl_vans WHERE v_id IN (" + vanIdsString + ")";
                java.sql.ResultSet rsVans = connector.getData(vanQuery);
                while (rsVans.next()) {
                    config.VanModel vm = new config.VanModel();
                    vm.setVid(rsVans.getInt("v_id"));
                    vm.setModel(rsVans.getString("model"));
                    vm.setVimage(rsVans.getString("image")); 
                    vans.add(vm);
                }
            }

            // 3. Prepare Stopovers (Empty for now)
            java.util.List<String> stops = new java.util.ArrayList<>();

            // 4. Open Details Frame
            app.BookingDetails details = new app.BookingDetails(bid, fullName, pUp, dest, sDate, eDate, tPrice, stat, vans, stops);
            details.setVisible(true);
            this.dispose();
        }
    } catch (java.sql.SQLException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error fetching details: " + ex.getMessage());
    }
}
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookingTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(76, 143, 209));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/goback.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 10, 60, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 60));

        bookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        bookingTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bookingTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 870, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bookingTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingTableMouseClicked
                                             
    int row = bookingTable.getSelectedRow();
    if (row != -1) {
        int bid = Integer.parseInt(bookingTable.getValueAt(row, 0).toString());
        openDetails(bid); 
    }


    }//GEN-LAST:event_bookingTableMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       customerDashboard cd = new customerDashboard();
       cd.setVisible(true);
       dispose();        
    }//GEN-LAST:event_jLabel1MouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookingList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookingList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookingList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookingList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookingList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bookingTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
