/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboard;


import app.BookingDetails;
import app.bookingList;
import app.landingPage;
import app.profile;
import fleet.fleet;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author RageKing
 */
public class customerDashboard extends javax.swing.JFrame {

    /**
     * Creates new form customerDashboard
     */
    public customerDashboard() {
        
        this.setUndecorated(true);
        initComponents();
        
         navbar.setBackground(java.awt.Color.decode("#010E22"));
        this.setShape(new java.awt.geom.RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20));
        
        System.out.println("DEBUG: Dashboard loaded for User ID: " + config.Session.getInstance().getId());
        
        if (config.Session.getInstance().getId() == 0) {
        JOptionPane.showMessageDialog(this, "Unauthorized access! Please login.");
        new app.loginForm().setVisible(true);
        this.dispose();
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 private void processBookingResult(java.sql.ResultSet rs) throws java.sql.SQLException {
    config.Session sess = config.Session.getInstance();
    
    // Extracting Data
    String bid = String.valueOf(rs.getInt("b_id"));
    String fullName = sess.getFirstname() + " " + sess.getLastname();
    String pUp = rs.getString("pick_up");
    String dest = rs.getString("destination");
    String sDate = rs.getString("start_date");
    String eDate = rs.getString("end_date");
    
    // Handle numeric total_price safely
    String tPrice = "₱" + rs.getDouble("total_price"); 
    String stat = rs.getString("status");
    
    // Map Van Info - Use "image" to match tbl_vans
    java.util.List<config.VanModel> vans = new java.util.ArrayList<>();
    config.VanModel vm = new config.VanModel();
    vm.setModel(rs.getString("model"));
    vm.setVimage(rs.getString("image")); 
    vans.add(vm);

    java.util.List<String> stops = new java.util.ArrayList<>();
    // Note: To get stopover names, you'd need a JOIN with tbl_stopovers

    // Open Details
    app.BookingDetails details = new app.BookingDetails(bid, fullName, pUp, dest, sDate, eDate, tPrice, stat, vans, stops);
    details.setVisible(true);
    this.dispose(); 
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        nav1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nav2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        bookings = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        history = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        mainpane = new javax.swing.JDesktopPane();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(76, 143, 209));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(76, 143, 209));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navbar.setBackground(new java.awt.Color(12, 33, 74));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nav1.setBackground(new java.awt.Color(2, 54, 85));
        nav1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nav1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nav1MouseExited(evt);
            }
        });
        nav1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PROFILE");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nav1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 14, 250, 20));

        navbar.add(nav1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 250, 50));

        nav2.setBackground(new java.awt.Color(2, 54, 85));
        nav2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nav2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nav2MouseExited(evt);
            }
        });
        nav2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BOOK NOW");
        nav2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 14, 240, 20));

        navbar.add(nav2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 250, 50));

        logout.setBackground(new java.awt.Color(2, 54, 85));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("LOGOUT");
        logout.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 14, 250, 20));

        navbar.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 250, 50));

        bookings.setBackground(new java.awt.Color(2, 54, 85));
        bookings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookingsMouseExited(evt);
            }
        });
        bookings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BOOKINGS");
        bookings.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 240, -1));

        navbar.add(bookings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 250, 60));

        history.setBackground(new java.awt.Color(2, 54, 85));
        history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyMouseClicked(evt);
            }
        });
        history.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("BOOKING HISTORY");
        history.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 250, -1));

        navbar.add(history, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 250, 60));

        jPanel2.add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 720));

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel3.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 30, 40));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeMouseReleased(evt);
            }
        });
        jPanel3.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 30, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 770, 40));

        mainpane.setBackground(new java.awt.Color(255, 255, 255));
        mainpane.setForeground(new java.awt.Color(154, 154, 238));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bluegb.JPG"))); // NOI18N
        mainpane.add(jLabel5);
        jLabel5.setBounds(0, 0, 780, 570);

        jPanel2.add(mainpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 770, 570));

        jPanel9.setBackground(new java.awt.Color(20, 20, 130));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CUSTOMER DASHBOARD");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 5, 770, -1));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 770, 110));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private int xMouse, yMouse;
    
    private void nav1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav1MouseClicked
                                    
    // Pass "Admin" so the profile knows who is logged in
    profile p = new profile("Customer"); 
    p.setVisible(true);
    this.dispose(); // Use dispose instead of setVisible(false) to save memory

    }//GEN-LAST:event_nav1MouseClicked

    private void nav2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav2MouseClicked
        fleet f = new fleet();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_nav2MouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
                                     
    int response = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "Are you sure you want to logout?", 
            "Logout Confirmation", 
            javax.swing.JOptionPane.YES_NO_OPTION, 
            javax.swing.JOptionPane.QUESTION_MESSAGE
    );

    if (response == javax.swing.JOptionPane.YES_OPTION) {
        
        config.Session sess = config.Session.getInstance();
        sess.setId(0);
        sess.setFirstname(null);
        sess.setLastname(null);
        sess.setEmail(null);
        sess.setType(null);
        sess.setStatus(null);

        System.out.println("DEBUG: Session has been successfully cleared.");
        app.landingPage lp = new app.landingPage();
        lp.setVisible(true);
        
     
        this.dispose();
    }


  

    }//GEN-LAST:event_logoutMouseClicked

    private void bookingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingsMouseClicked
                                  
                                    
    new app.bookingList("Bookings").setVisible(true);
    //bl.displayTable(); // Load the data immediately
    this.dispose();





    }//GEN-LAST:event_bookingsMouseClicked

    private void nav1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav1MouseEntered
         nav1.setBackground(java.awt.Color.decode("#256B97"));
    }//GEN-LAST:event_nav1MouseEntered

    private void nav1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav1MouseExited
        nav1.setBackground(java.awt.Color.decode("#233E5C"));
    }//GEN-LAST:event_nav1MouseExited

    private void nav2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav2MouseEntered
          nav2.setBackground(java.awt.Color.decode("#256B97"));
    }//GEN-LAST:event_nav2MouseEntered

    private void nav2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav2MouseExited
         nav2.setBackground(java.awt.Color.decode("#233E5C"));
    }//GEN-LAST:event_nav2MouseExited

    private void bookingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingsMouseEntered
        bookings.setBackground(java.awt.Color.decode("#256B97"));
    }//GEN-LAST:event_bookingsMouseEntered

    private void bookingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingsMouseExited
         bookings.setBackground(java.awt.Color.decode("#233E5C"));
    }//GEN-LAST:event_bookingsMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
          logout.setBackground(java.awt.Color.decode("#256B97"));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
         logout.setBackground(java.awt.Color.decode("#233E5C"));
    }//GEN-LAST:event_logoutMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
    int confirm = javax.swing.JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Exit", javax.swing.JOptionPane.YES_NO_OPTION);
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_closeMouseClicked

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
       close.setForeground(java.awt.Color.RED);
    }//GEN-LAST:event_closeMousePressed

    private void closeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseReleased
        close.setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_closeMouseReleased

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
       this.setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
      xMouse = evt.getX();
      yMouse = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
    int x = evt.getXOnScreen();
    int y = evt.getYOnScreen();
    this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void historyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyMouseClicked
     new app.bookingList("History").setVisible(true);
     this.dispose();
    }//GEN-LAST:event_historyMouseClicked

    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bookings;
    private javax.swing.JLabel close;
    private javax.swing.JPanel history;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel logout;
    private javax.swing.JDesktopPane mainpane;
    private javax.swing.JLabel minimize;
    private javax.swing.JPanel nav1;
    private javax.swing.JPanel nav2;
    private javax.swing.JPanel navbar;
    // End of variables declaration//GEN-END:variables
}
