/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboard;


import app.BookingDetails;
import app.bookingList;
import app.landingPage;
import app.profile;
import fleet.fleet;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author RageKing
 */
public class customerDashboard extends javax.swing.JFrame {

    /**
     * Creates new form customerDashboard
     */
    public customerDashboard() {
        initComponents();
        
        System.out.println("DEBUG: Dashboard loaded for User ID: " + config.Session.getInstance().getId());
        
        if (config.Session.getInstance().getId() == 0) {
        JOptionPane.showMessageDialog(this, "Unauthorized access! Please login.");
        new app.loginForm().setVisible(true);
        this.dispose();
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 private void processBookingResult(java.sql.ResultSet rs) throws java.sql.SQLException {
    config.Session sess = config.Session.getInstance();
    
    // Extracting Data
    String bid = String.valueOf(rs.getInt("b_id"));
    String fullName = sess.getFirstname() + " " + sess.getLastname();
    String pUp = rs.getString("pick_up");
    String dest = rs.getString("destination");
    String sDate = rs.getString("start_date");
    String eDate = rs.getString("end_date");
    
    // Handle numeric total_price safely
    String tPrice = "₱" + rs.getDouble("total_price"); 
    String stat = rs.getString("status");
    
    // Map Van Info - Use "image" to match tbl_vans
    java.util.List<config.VanModel> vans = new java.util.ArrayList<>();
    config.VanModel vm = new config.VanModel();
    vm.setModel(rs.getString("model"));
    vm.setVimage(rs.getString("image")); 
    vans.add(vm);

    java.util.List<String> stops = new java.util.ArrayList<>();
    // Note: To get stopover names, you'd need a JOIN with tbl_stopovers

    // Open Details
    app.BookingDetails details = new app.BookingDetails(bid, fullName, pUp, dest, sDate, eDate, tPrice, stat, vans, stops);
    details.setVisible(true);
    this.dispose(); 
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        nav1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nav2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        bookings = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        mainpane = new javax.swing.JDesktopPane();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(76, 143, 209));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(76, 143, 209));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navbar.setBackground(new java.awt.Color(153, 0, 204));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nav1.setBackground(new java.awt.Color(204, 102, 255));
        nav1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav1MouseClicked(evt);
            }
        });
        nav1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PROFILE");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nav1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 14, 250, 20));

        navbar.add(nav1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 250, 50));

        nav2.setBackground(new java.awt.Color(204, 102, 255));
        nav2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav2MouseClicked(evt);
            }
        });
        nav2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BOOK NOW");
        nav2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 14, 240, 20));

        navbar.add(nav2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 250, 50));

        logout.setBackground(new java.awt.Color(204, 102, 255));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("LOGOUT");
        logout.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 14, 250, 20));

        navbar.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 250, 50));

        bookings.setBackground(new java.awt.Color(204, 102, 255));
        bookings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingsMouseClicked(evt);
            }
        });
        bookings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BOOKINGS");
        bookings.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 240, -1));

        navbar.add(bookings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 250, 60));

        jPanel2.add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 720));

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 770, 40));

        mainpane.setBackground(new java.awt.Color(154, 154, 238));
        mainpane.setForeground(new java.awt.Color(154, 154, 238));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/violetbg.JPG"))); // NOI18N
        mainpane.add(jLabel7);
        jLabel7.setBounds(0, -30, 770, 600);

        jPanel2.add(mainpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 770, 570));

        jPanel9.setBackground(new java.awt.Color(154, 154, 238));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CUSTOMER DASHBOARD");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel9.add(jLabel1);

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 770, 110));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nav1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav1MouseClicked
                                    
    // Pass "Admin" so the profile knows who is logged in
    profile p = new profile("Customer"); 
    p.setVisible(true);
    this.dispose(); // Use dispose instead of setVisible(false) to save memory

    }//GEN-LAST:event_nav1MouseClicked

    private void nav2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav2MouseClicked
        fleet f = new fleet();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_nav2MouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
                                        
    int response = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "Are you sure you want to logout?", 
            "Logout Confirmation", 
            javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (response == javax.swing.JOptionPane.YES_OPTION) {
        // 1. CLEAR THE SESSION DATA
        config.Session.getInstance().clearSession();
        
        // 2. REDIRECT TO LOGIN/LANDING
        app.landingPage lp = new app.landingPage();
        lp.setVisible(true);
        
        // 3. CLOSE CURRENT FRAME
        this.dispose();
    }

  

    }//GEN-LAST:event_logoutMouseClicked

    private void bookingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingsMouseClicked
                                  
                                    
    bookingList bl = new bookingList();
    bl.setVisible(true);
    bl.displayTable(); // Load the data immediately
    this.dispose();





    }//GEN-LAST:event_bookingsMouseClicked

    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bookings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel logout;
    private javax.swing.JDesktopPane mainpane;
    private javax.swing.JPanel nav1;
    private javax.swing.JPanel nav2;
    private javax.swing.JPanel navbar;
    // End of variables declaration//GEN-END:variables
}
